DROP TABLE IF EXISTS "example";

CREATE TABLE "example" (
  id SERIAL PRIMARY KEY,
  Name varchar(255) default NULL,
  Country varchar(100) default NULL,
  Email varchar(255) default NULL
);

INSERT INTO "example" (Name,Country,Email) VALUES ('Dante V. Joseph','Hong Kong','mollis.Duis@ligulaNullamfeugiat.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Carson T. Ingram','Libya','nibh.Donec.est@nec.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Driscoll H. Rivers','Uzbekistan','neque@vitaeposuereat.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Duncan X. Stewart','Turkey','nulla.In.tincidunt@maurisMorbinon.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hillary N. Wolfe','Cook Islands','pede@euismodac.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Jenette R. Conrad','Pakistan','adipiscing.elit.Etiam@adipiscing.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Connor U. Trevino','Guernsey','mauris@duiquis.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Barbara R. Johnston','Cuba','mi.pede.nonummy@Morbi.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Shana Y. Morrison','Solomon Islands','ante.ipsum@Phasellusataugue.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hop C. Estes','Mauritania','ac@vulputate.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hayden T. Rush','American Samoa','ut@gravidasitamet.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Larissa Z. Dickerson','Singapore','ipsum@lacus.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kane N. Talley','Morocco','feugiat.metus@mollisPhasellus.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Irene S. Wallace','Samoa','pharetra.Quisque@arcuVestibulumante.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Aretha C. Garner','Georgia','ac.fermentum.vel@sedpedeCum.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Tatyana N. Blackwell','Haiti','sit@nullaInteger.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Mariam D. Decker','Zambia','mauris.blandit@sociisnatoquepenatibus.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Oscar V. Robbins','Albania','Curae.Donec.tincidunt@adipiscing.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Lilah I. Drake','Kazakhstan','diam@torquentperconubia.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Ebony T. Ray','Mauritania','ligula.Aenean.gravida@milaciniamattis.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Carissa T. Gibson','Taiwan','eros.Nam@quam.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kaitlin U. Tran','Bosnia and Herzegovina','augue.porttitor@consequatdolorvitae.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Rhoda D. Weiss','Luxembourg','lectus.Cum@Integertinciduntaliquam.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Nash K. Little','Oman','sit.amet@ultricesaauctor.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Tallulah Q. Mcintyre','Wallis and Futuna','Aenean.egestas@etrutrumnon.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hoyt G. Wooten','Montserrat','Suspendisse.dui@nuncidenim.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Quintessa J. Holt','Cuba','orci.Phasellus@faucibus.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Ivy V. Kent','French Southern Territories','urna.justo@euodio.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Rogan D. Mendoza','New Zealand','ornare@amet.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Xyla X. David','Bermuda','felis@acnulla.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Jason I. Sharpe','Ireland','quam@gravidaAliquamtincidunt.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Lara D. Oneil','Costa Rica','Integer@tellusNunc.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Medge G. Blackburn','Bahrain','ornare.elit.elit@arcueu.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Angela G. King','Trinidad and Tobago','molestie.tellus.Aenean@risus.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Sybill O. Mcintyre','Suriname','Maecenas.mi@cursusa.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Brian O. Head','Pitcairn Islands','arcu.vel@nislelementum.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Florence L. Greer','Singapore','auctor.velit@odiosagittis.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Gisela L. Valenzuela','Qatar','mauris.ut.mi@anteipsumprimis.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Richard Y. Dotson','Malta','vitae@Aliquamornare.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Camden M. Harris','Jordan','ultrices.a.auctor@tristiquepellentesque.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Sawyer L. Mcknight','Papua New Guinea','sem.Nulla@leoVivamusnibh.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Montana X. Patel','Sierra Leone','eleifend.egestas@Suspendissenonleo.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Perry A. Sparks','French Southern Territories','ligula.consectetuer.rhoncus@nullaInteger.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Regina H. Randall','Equatorial Guinea','sodales.nisi.magna@amet.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hayley N. Wheeler','Guinea-Bissau','iaculis.quis.pede@orciconsectetuer.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kelsie Z. Myers','Bahamas','sem.Pellentesque@velitPellentesqueultricies.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hilary X. Roberson','Malawi','magna.malesuada.vel@nibhsitamet.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Micah G. Brock','Christmas Island','sed.pede@vulputate.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Astra U. Mcfadden','Swaziland','id@lacusMaurisnon.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Caryn W. Collier','Taiwan','pretium.neque@odio.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Uriah E. Faulkner','Qatar','Mauris@Morbineque.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Grace T. Grant','Serbia','Quisque.ac.libero@orciPhasellus.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Mary C. Reese','Mozambique','Integer.tincidunt@Aenean.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Xaviera D. Martin','Sudan','non.dui@porttitorvulputate.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Honorato J. Goff','Falkland Islands','sagittis.felis.Donec@Maurisnondui.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kerry K. William','Jordan','natoque@ipsumSuspendisse.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Montana J. Frank','Cayman Islands','sagittis@libero.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Price T. Howe','Saudi Arabia','pharetra@atvelit.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Guinevere D. Guy','Samoa','et.magnis@Sedpharetrafelis.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Vera P. May','Taiwan','vitae@Donectemporest.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Daquan W. Rivera','Chad','ac.mi@Phasellusdapibusquam.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Alyssa B. Fischer','Japan','quis.pede@ategestasa.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Garrison Z. Powell','Heard Island and Mcdonald Islands','at.arcu.Vestibulum@pedemalesuadavel.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Carolyn W. Marshall','Saint Pierre and Miquelon','ac@sitametante.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Sebastian S. Savage','United Kingdom (Great Britain)','vulputate@et.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Duncan I. Reilly','Argentina','malesuada.vel@dapibusrutrumjusto.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Ishmael V. Hendrix','Gibraltar','litora.torquent@Morbinequetellus.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Christopher V. Blevins','Nepal','molestie@enimcondimentum.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Hashim F. Wise','Malawi','Donec@idnunc.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Patricia I. Puckett','Tunisia','accumsan@molestiesodalesMauris.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Macaulay X. Paul','Moldova','neque.pellentesque.massa@Nulladignissim.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Tanisha T. Kelley','Ecuador','tortor.Nunc.commodo@sedhendrerit.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Benjamin B. Combs','Denmark','pede@vulputateduinec.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Cara I. Mccray','Belize','Curae.Donec.tincidunt@sitametornare.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Mark Y. Christian','South Africa','dui.nec.tempus@enimgravida.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kylie S. Roberts','Egypt','in@ipsumnon.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Alea A. Gallagher','Macao','ridiculus.mus@odio.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Madaline G. Fry','United Kingdom (Great Britain)','torquent.per.conubia@Cum.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Raymond D. Alvarado','China','mauris.Morbi@Craseu.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kermit G. Stokes','Georgia','purus@vitaeerat.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('MacKenzie R. Ayers','Dominican Republic','nec.mollis@ligula.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Jesse M. Wiley','Australia','ut.erat.Sed@orci.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Magee G. Mcfarland','Saint Vincent and The Grenadines','enim.Mauris@lectuspedeultrices.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Leandra X. Nolan','Ireland','ornare.libero.at@Mauris.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Harriet U. Hines','Chad','blandit.congue@fringilla.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Winifred G. Bennett','Switzerland','montes.nascetur@Vestibulumuteros.edu');
INSERT INTO "example" (Name,Country,Email) VALUES ('Joshua V. Howard','Tokelau','nisi@sit.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Thane J. Romero','Kyrgyzstan','dictum@ProinultricesDuis.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Ivana Y. Vaughn','Hungary','amet@nuncnulla.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Jarrod F. Wolfe','Bermuda','dolor.Donec.fringilla@dolor.ca');
INSERT INTO "example" (Name,Country,Email) VALUES ('Stacey K. Erickson','Trinidad and Tobago','molestie.arcu@erosProinultrices.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Demetrius U. Buckley','Cape Verde','nunc.sed@variusNamporttitor.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Neville T. Craft','Jordan','vulputate.eu@veliteget.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Rahim A. Carlson','Yemen','Aliquam.auctor@a.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Sylvia E. Berry','El Salvador','mauris.Morbi.non@vulputateeuodio.org');
INSERT INTO "example" (Name,Country,Email) VALUES ('Solomon R. Tanner','Guernsey','diam@adipiscing.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Mary K. Acosta','Albania','nibh@massa.com');
INSERT INTO "example" (Name,Country,Email) VALUES ('Kirsten P. Lambert','Guernsey','Mauris@congueelit.co.uk');
INSERT INTO "example" (Name,Country,Email) VALUES ('Mari W. Fulton','Eritrea','ligula.tortor@mauris.net');
INSERT INTO "example" (Name,Country,Email) VALUES ('Jolene R. Pacheco','United States Minor Outlying Islands','eros.non.enim@sem.co.uk');
