DROP TABLE IF EXISTS "sample";

CREATE TABLE "sample" (
  id SERIAL PRIMARY KEY,
  Name varchar(255) default NULL,
  Country varchar(100) default NULL,
  Email varchar(255) default NULL
);

INSERT INTO "sample" (Name,Country,Email) VALUES ('Xenos O. Perkins','Denmark','velit.dui.semper@magnaUt.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Igor A. Beach','Kuwait','Nunc.sollicitudin@egestasurna.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Baker D. Smith','Timor-Leste','dolor.Donec.fringilla@Vestibulumante.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Fallon Z. Payne','Cayman Islands','ipsum@lobortistellusjusto.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Cameron S. Ellison','United Kingdom (Great Britain)','tincidunt@ante.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Tad P. Reeves','United States','Fusce.fermentum@montes.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Joelle H. Chen','India','Duis.gravida.Praesent@CraspellentesqueSed.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Cherokee K. Mullen','Guatemala','Suspendisse.commodo@rutrum.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Iola V. Haney','Equatorial Guinea','mauris@Integer.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Scarlett K. Howell','Malaysia','Cras.sed@Duis.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Charles T. Mcmahon','Portugal','habitant.morbi.tristique@augue.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Uta T. Weaver','Norfolk Island','malesuada.Integer@egestasurnajusto.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Rachel Q. Faulkner','Italy','vulputate.risus@molestie.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Deborah T. Lloyd','Ireland','vitae@Morbi.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Alana C. French','Central African Republic','quis.tristique@Nullamvelit.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Gavin A. Guerra','Guernsey','non.egestas@a.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Nora M. Stone','Uganda','nonummy@pedesagittisaugue.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Josephine J. Carpenter','Kuwait','lobortis@ante.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Echo F. Myers','Samoa','eu.ultrices@atlacus.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Lillian X. Finley','Madagascar','mi@dolorquamelementum.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('TaShya S. Valentine','Denmark','Cras.eu.tellus@vel.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Jaime Y. Chavez','Bosnia and Herzegovina','neque@Fuscedolorquam.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Cadman Z. Williams','India','nisi.magna.sed@molestiesodalesMauris.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Arsenio U. Weeks','China','adipiscing@et.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Amanda A. Joyner','Norway','ac@senectus.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Eden G. Richards','Norfolk Island','enim@etnuncQuisque.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Graham V. Dominguez','Niue','ligula.Nullam.enim@Etiambibendum.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Katell I. Bartlett','Spain','non@Praesenteu.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Miranda Z. Hendricks','Oman','rutrum.eu.ultrices@tristiquepharetra.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Maxine U. Jenkins','Malta','Nulla.aliquet@parturientmontesnascetur.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Inez I. Decker','Ukraine','semper@nisiMauris.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Idona P. Stewart','Côte D''Ivoire (Ivory Coast)','dictum.cursus.Nunc@dignissimmagnaa.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Sylvester S. Dominguez','Liechtenstein','dolor.quam@mauris.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kimberly P. Estrada','France','vestibulum.Mauris.magna@commodoauctor.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Eaton H. Horn','Nicaragua','faucibus.Morbi@NulladignissimMaecenas.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Farrah S. Castaneda','United States','nec@egestasAliquam.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Evangeline N. Estrada','Equatorial Guinea','Fusce@a.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Destiny R. Merritt','Hungary','eros.turpis.non@Nulla.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Hedda L. Albert','Saint Lucia','mattis.ornare.lectus@diam.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Jamal O. Combs','Guyana','blandit.at@Nullamscelerisque.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Buckminster C. Norton','Tunisia','hendrerit.id.ante@nullaCraseu.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Ina O. Mejia','Turkey','lorem.ipsum@nequeIn.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Hayden S. Chapman','Brunei','Sed.malesuada@atfringilla.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kiona F. Vaughn','Albania','lacus.Nulla.tincidunt@orci.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Tarik R. Baxter','Israel','at.augue@Phasellusataugue.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Quentin K. Meyers','Liberia','libero.nec.ligula@dolorsitamet.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Derek P. Dorsey','Seychelles','velit.justo@urnaetarcu.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Zephr Y. Wilcox','Latvia','Fusce.aliquam@seddictumeleifend.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Ashton U. Suarez','Palau','egestas@Suspendissealiquetmolestie.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Cassidy J. Webster','Samoa','nec.metus@tellus.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Taylor Y. Ramos','Reunion','Ut.tincidunt.vehicula@idenimCurabitur.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Phillip J. Holloway','Cameroon','augue.eu@Donecest.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Lara O. Ingram','Armenia','enim@mi.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Rowan Q. Welch','Rwanda','erat.neque@FuscefeugiatLorem.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Palmer J. Hayden','Benin','Sed.congue.elit@lacusAliquam.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Drew U. Aguilar','Guinea','Duis@orciadipiscingnon.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Rudyard P. Beck','Comoros','facilisis@tristiquepharetraQuisque.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Maryam T. Pace','Bermuda','vitae.orci@tempusrisus.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Rose U. Wall','Mozambique','Proin.vel@nunc.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Brody S. Merritt','Hong Kong','Curabitur@auctorvelit.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Claire T. Gomez','Montserrat','nunc@enimEtiam.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Wanda G. Carver','Korea, South','ut.ipsum.ac@Nullam.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Wayne I. Levy','Bermuda','luctus.ut.pellentesque@antedictum.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Athena D. Barber','Singapore','et@Vestibulumut.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Alyssa M. Fuller','Bangladesh','vel@Morbinonsapien.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Suki T. Hubbard','Tokelau','ut.ipsum.ac@molestieSedid.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Sonya I. Ross','Andorra','Fusce.fermentum.fermentum@utmolestiein.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Ivor U. David','South Georgia and The South Sandwich Islands','nec.euismod.in@lacusvestibulum.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Herman Q. Good','Nauru','libero@amagnaLorem.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Grady P. Barlow','Qatar','Aenean@inmolestie.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Colleen L. Macias','Mayotte','magna@atiaculisquis.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Darius T. Cardenas','Marshall Islands','egestas.ligula@semut.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Helen Z. Christian','Tonga','sem.elit@eratSednunc.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Jenette Q. Calderon','Trinidad and Tobago','ligula.Aliquam@penatibuset.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Ronan E. Melton','Greenland','leo.Vivamus@vestibulumloremsit.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Audra N. Weber','Solomon Islands','ac.eleifend.vitae@et.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Jasper C. Mckay','Japan','nec.ante.blandit@dignissimlacus.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kennan W. Lamb','Haiti','nisi.magna.sed@luctus.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Martin P. Finch','Bosnia and Herzegovina','volutpat.ornare.facilisis@nisi.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Dorothy S. Young','Belarus','mauris.eu@rutrumjustoPraesent.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Whilemina T. Hayden','Spain','faucibus.id.libero@imperdietnonvestibulum.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kirsten E. Savage','Lebanon','odio.auctor@Pellentesque.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kamal F. Petty','Wallis and Futuna','elementum.purus.accumsan@aliquam.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Lilah U. Holman','Pakistan','Fusce.feugiat.Lorem@vel.edu');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Kylynn D. Fitzpatrick','Malaysia','tincidunt.neque.vitae@Innec.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Duncan Z. Ratliff','Djibouti','ornare.In@in.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Justine F. Miles','Saint Vincent and The Grenadines','tincidunt@dapibus.net');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Elizabeth O. Brown','Belgium','Nunc.mauris.sapien@sollicitudinadipiscing.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Stuart C. Gallagher','Saint Kitts and Nevis','justo.Praesent.luctus@turpis.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Shelley G. Mcguire','Peru','diam.Duis.mi@nibhPhasellusnulla.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Evan L. Pearson','Turkey','at.velit.Cras@facilisis.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Shelby T. Hoffman','Comoros','sociis.natoque@at.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Katelyn E. Hewitt','Guyana','tempor.erat@ornare.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Henry V. Bauer','Antigua and Barbuda','vitae.odio.sagittis@nec.co.uk');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Serina D. English','El Salvador','imperdiet@ut.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Shellie F. Mccarty','Kyrgyzstan','malesuada.id.erat@etpedeNunc.org');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Cailin C. French','Belize','orci@posuere.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Harriet Q. Mercado','Syria','sagittis@eleifendCrassed.com');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Alexandra E. Roberts','Saudi Arabia','sed.sem@sagittis.ca');
INSERT INTO "sample" (Name,Country,Email) VALUES ('Jacob W. Vazquez','Liechtenstein','imperdiet.dictum@Donecnibhenim.org');
