DROP TABLE IF EXISTS "PeopleTwo";

CREATE TABLE "PeopleTwo" (
  id SERIAL PRIMARY KEY,
  Name varchar(255) default NULL,
  Country varchar(100) default NULL,
  Age integer NULL,
  Wage integer NULL
);

INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Harriet S. Carver','Bahamas',19,36407);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Paul W. Owens','Argentina',52,48457);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Harding P. Noble','Canada',54,14115);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Veronica C. Blackwell','Saint Vincent and The Grenadines',52,32024);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Irene J. Hampton','Suriname',29,66696);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Myles L. Knapp','Saint Pierre and Miquelon',21,47574);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Demetria G. Nunez','Nepal',36,45042);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Cleo L. Pickett','Paraguay',60,11302);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Justine O. Weaver','South Africa',50,67496);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Ignatius Z. Haynes','Namibia',38,69608);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Amal P. Lynch','Austria',22,26902);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Ignatius H. Mcknight','Lebanon',61,80439);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Aladdin W. Holden','Lesotho',60,16207);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Morgan U. Kim','Rwanda',33,29751);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Belle U. Cross','Mauritius',29,87033);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Jerome C. Nolan','Sudan',31,70432);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Serena U. Sargent','Curaçao',57,28480);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brady U. Cooke','Guyana',24,37481);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Gillian D. Watkins','Mauritania',38,44899);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Caleb S. Salazar','Heard Island and Mcdonald Islands',74,81214);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Simon T. Rowe','Saint Martin',18,54518);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brynne R. Cruz','Singapore',44,22425);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Shaine J. Sellers','Grenada',46,33932);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Chadwick J. Hunter','Azerbaijan',65,85140);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Plato I. Key','Portugal',40,65870);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Darrel L. Carpenter','French Guiana',61,82244);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Nomlanga G. Booker','Angola',67,39707);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Lynn Y. Madden','Madagascar',45,19826);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Abbot D. Watkins','Palestine, State of',24,43581);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Branden G. Levine','Czech Republic',38,70259);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Luke A. Jensen','Ghana',69,80334);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Maia B. Fry','New Caledonia',47,63491);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Conan J. Velazquez','Comoros',64,67282);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Xena X. Phillips','Saint Barthélemy',46,47518);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Moses Z. Roberts','Somalia',51,48697);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brenna M. Lloyd','France',34,12656);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Lance C. Norris','Cayman Islands',60,29434);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Keelie P. Kennedy','Guernsey',38,90614);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kasper I. Benton','Burundi',59,43070);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Timon H. Hubbard','Honduras',71,36286);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Karly K. Hensley','Malta',18,61432);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kalia I. Hines','French Polynesia',63,47323);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Serina X. Wilcox','Somalia',54,74063);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brynne X. Morse','Malta',34,12093);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brielle T. Le','Philippines',33,55848);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Simone U. Winters','Lithuania',68,19930);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Yetta U. Hamilton','French Southern Territories',30,15496);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Forrest H. Price','Cocos (Keeling) Islands',49,10985);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Iris I. Bauer','Georgia',69,14854);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Aphrodite N. Jacobs','Luxembourg',30,43118);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Lewis Y. Best','Bermuda',41,37358);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Abel U. Wilcox','French Southern Territories',64,19319);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Shoshana Y. Mcgowan','Australia',37,25203);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Moses R. Kirby','Gibraltar',58,76815);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Jescie Q. Cash','Philippines',50,89774);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Ella O. Morrison','Cyprus',18,94723);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Sloane U. Blair','Tajikistan',48,70003);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kenneth P. Hale','Dominican Republic',27,24490);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Aidan B. Bernard','Guam',61,22392);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Charles B. Hopper','Czech Republic',71,78147);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Lee I. Ellis','Sao Tome and Principe',68,46899);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Iris Z. Maynard','Latvia',59,35964);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Colton A. Lyons','Kiribati',26,41323);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Brianna J. Owen','Haiti',57,52816);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Mikayla D. Barrera','United Arab Emirates',31,75668);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kylie I. Becker','Anguilla',59,15325);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Quincy O. Grant','Sao Tome and Principe',71,38879);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Erica R. Sanders','Pitcairn Islands',39,15546);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Nina Z. Moses','Sierra Leone',36,65570);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Zena H. Crosby','Norway',67,95366);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kermit V. Lowe','Kazakhstan',68,34713);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Olga I. Lang','Korea, South',62,77708);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Wesley J. Mckay','Jamaica',34,44566);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Dane Y. Jordan','Guadeloupe',58,86847);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Graham O. Glover','Reunion',47,47471);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Yeo J. Knox','Falkland Islands',48,13077);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Libby X. Wilson','Sao Tome and Principe',32,76668);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Vivian I. Massey','Kenya',68,43054);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Edward J. Andrews','Dominican Republic',22,68793);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Zephania M. Orr','Antarctica',33,53853);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Rinah I. Stevenson','Turkmenistan',33,94671);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Alice X. Berger','Saint Lucia',30,96831);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Carter J. Wong','Austria',36,60391);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Kasper Y. Keith','China',64,39152);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Rina F. Cameron','British Indian Ocean Territory',26,65598);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Tad B. Hester','Maldives',72,46359);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Bradley D. Ramos','Gambia',47,54626);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Griffin T. Patton','Algeria',31,15099);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Paki N. Mullins','Azerbaijan',32,11077);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Ulric B. Navarro','Saint Kitts and Nevis',61,62993);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Vivian C. Shields','San Marino',31,18965);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Maisie M. Cervantes','Bulgaria',20,19074);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Cathleen K. Scott','Falkland Islands',27,35956);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Eugenia E. Walters','Germany',28,62372);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Tatiana K. Charles','Kenya',21,13227);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Danielle Z. Underwood','Estonia',41,46834);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Chandler T. Santana','Viet Nam',46,29755);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Oprah O. Bowman','Martinique',41,20285);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Hop A. Rhodes','India',56,72952);
INSERT INTO "PeopleTwo" (Name,Country,Age,Wage) VALUES ('Grant W. Dunlap','San Marino',66,75368);
