DROP TABLE IF EXISTS "People";

CREATE TABLE "People" (
  id SERIAL PRIMARY KEY,
  Name varchar(255) default NULL,
  Country varchar(100) default NULL,
  Age integer NULL,
  Wage integer NULL
);

INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Hedy S. Washington','Rwanda',18,92211);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Hakeem O. Campos','Jordan',18,70371);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Vera A. Wilson','Ghana',24,12276);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Uriel S. Vaughan','Cook Islands',74,41285);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Baxter W. Byers','Liberia',34,26827);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Eugenia A. Duke','Austria',23,71944);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Maggy O. Haynes','Benin',67,69984);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Thomas T. Padilla','Puerto Rico',44,76118);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Martena K. Walter','Zimbabwe',41,57279);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jolie G. Pearson','Hong Kong',74,91513);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Austin T. Acevedo','Egypt',55,96218);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Anastasia W. Morales','Czech Republic',71,70449);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Rae Q. Paul','Argentina',69,34148);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Rana J. Oliver','Norway',45,43521);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Carson E. Johnston','Puerto Rico',41,61158);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Bevis P. Hensley','Bouvet Island',64,56918);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Irma M. Rowe','Central African Republic',47,94721);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Warren V. Blanchard','Djibouti',70,33582);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Serena R. Mcconnell','Bermuda',18,78529);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Micah I. Nunez','Solomon Islands',23,78533);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Fiona O. Fuller','Mozambique',19,76384);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ali A. Nolan','Kazakhstan',18,69036);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Heidi N. Carlson','Dominican Republic',40,44282);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Darryl X. Miller','Spain',49,71566);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Boris T. Gonzales','Angola',25,47155);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Katelyn A. Stout','Montserrat',52,74302);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Justine Z. Williamson','Saudi Arabia',74,24532);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Rajah H. Buckner','Korea, South',60,61409);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Priscilla U. Pratt','Holy See (Vatican City State)',25,88615);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Matthew X. Mcdonald','Sint Maarten',69,66785);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Katell W. Griffin','Gambia',72,63177);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Yoshi Z. Michael','Guinea',75,22188);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Barbara I. Shepard','Venezuela',22,38310);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Garrison C. Shaffer','Syria',32,56452);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Brandon P. Stevens','Chad',50,30597);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Hayfa B. Ware','Madagascar',65,58974);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Macaulay X. Ray','Chad',22,88666);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Burton Q. Tillman','San Marino',54,78717);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Graham I. Mathews','Chad',56,47527);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Kadeem V. Lindsey','Croatia',43,70960);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Emery W. Rivas','Chile',28,46298);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Rowan O. Crane','Switzerland',37,17611);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jessamine A. Hull','Pakistan',53,16076);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jackson R. Young','Cayman Islands',55,92375);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Julie P. Hanson','Australia',20,48900);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ian M. Haynes','Chile',31,72205);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Caesar L. Mack','Equatorial Guinea',29,13748);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Camilla M. Mcmillan','Timor-Leste',27,12462);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Henry H. Cain','China',23,91436);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Dillon Y. Mckay','Mauritania',69,99899);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ulla Q. Guerrero','Palau',25,19364);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Kylynn C. Parks','Grenada',61,34026);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Tanner H. Reynolds','Seychelles',65,88208);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Alisa E. Greer','Oman',59,36310);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Isabella Z. Sargent','Sao Tome and Principe',72,97904);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Clarke O. Dotson','Finland',66,52499);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Priscilla N. Barlow','Saint Pierre and Miquelon',25,23216);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jermaine S. Mosley','Japan',55,38927);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Xanthus U. Daugherty','Japan',48,75128);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ira B. Suarez','Luxembourg',67,94213);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Octavia F. Howard','Tunisia',36,63967);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jacqueline D. Gutierrez','South Sudan',69,36720);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Florence J. Paul','Sweden',56,11817);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Hedy J. Phelps','Guyana',38,58895);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Anne V. Mooney','Barbados',52,99505);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Bernard M. Roach','Bonaire, Sint Eustatius and Saba',22,15585);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Hedy J. Hubbard','United States Minor Outlying Islands',18,11811);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Lois C. Luna','Greece',19,68813);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Adena M. Guzman','Somalia',26,77838);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Joan D. Schwartz','Mayotte',74,98738);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Todd R. Clarke','French Polynesia',22,25353);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ima K. Collier','Bermuda',45,32764);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Meghan P. Ochoa','Kiribati',66,81453);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Heidi I. Christensen','Malta',26,69749);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Palmer J. Raymond','India',58,47068);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Mason X. Browning','Heard Island and Mcdonald Islands',54,77463);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Chava H. Wyatt','Mongolia',67,40091);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Fleur U. Mcfarland','Rwanda',22,86037);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Buckminster X. Melton','Bahamas',75,40538);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Candice X. Ray','Faroe Islands',70,56066);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Jade U. Morton','Afghanistan',61,15072);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('John P. Mcgowan','Greece',19,36614);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Suki M. Robbins','Austria',63,10578);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Nissim U. Barlow','Burundi',49,79374);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Audrey R. Ellis','Honduras',70,86291);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Yolanda R. Gibbs','Isle of Man',25,63746);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Kameko L. Vang','Portugal',47,37465);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Tanya L. Mckenzie','Mozambique',61,29003);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Philip B. Holloway','Kyrgyzstan',65,10303);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Alyssa B. Campos','Egypt',42,80198);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Wynter E. Boone','Timor-Leste',69,30589);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Nerea L. Ortiz','Germany',70,72682);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Felicia I. Harris','Moldova',43,54266);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Omar D. Mcconnell','Korea, South',72,72634);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Driscoll E. Valentine','Vanuatu',55,84454);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Imogene U. Goff','Qatar',55,81825);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Kane K. Bray','United States Minor Outlying Islands',73,92469);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Ryan N. Rhodes','Isle of Man',68,73042);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Stella T. Moran','Guinea-Bissau',28,46169);
INSERT INTO "People" (Name,Country,Age,Wage) VALUES ('Kristen N. Taylor','Romania',54,99075);

SELECT * FROM "People";
